theme: jekyll-theme-midnight
<script src="https://utteranc.es/client.js"
        repo="https://github.com/i0uthis/blog.intp-362"
        issue-term="pathname"
        theme="github-dark"
        crossorigin="anonymous"
        async>
</script>
